---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: currencyexchange
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: currencyexchange-deployment
        version: v1
    spec:
      containers:
        - name: currencyexchange
          image: grantsteinfeldibm/currencyexchange:v0.0.1
          imagePullPolicy: Always
          env:
            - name: HOST_IP
              value: <INGRESS_SUBDOMAIN>
          ports:
            - containerPort: 4001

---
apiVersion: v1
kind: Service
metadata:
  name: currencyexchange-service
spec:
  ports:
    - port: 4001
      targetPort: 4001
      nodePort: 32001
      name: http
  type: NodePort
  selector:
    name: currencyexchange-deployment
